[tool.black]
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.mypy_cache
  | \.tox
  | \.venv
  | \.vscode
  | \.eggs
  | _build
  | buck-out
  | build
  | dist
  | docs
)/
'''

[tool.isort]
profile = "black"

[tool.ruff]
line-length = 88
target-version = "py38"
select = ["ALL"]
ignore = [
    "ANN",
    "S101",
    "D1",
    "D400",
    "D415",
    "D203",
    "D200", # One-line docstring should fit on one line
    "D212",
    "D213", # Multi-line docstring summary should start at the second line
    "E402", # Module level import not at top of file
    "FBT",  # Boolean checks
    "SIM105",
    "SIM108",
    "DTZ",
    "EM",
    "ERA001",
    "PT004", # Fixture does not return anything, add leading underscore
    "C",
    "B905",
    "BLE001",
    "T",
    "RET",
    "SIM117", # Use a single `with` statement with multiple contexts instead of nested `with` statements
    "PGH004", # Use specific error codes when using `noqa`
]
extend-exclude = [
    "docs",
]

[tool.ruff.per-file-ignores]
"__init__.py" = ["E402", "F401", "F403"]
"command_sets.py" = ["ARG001"]
"**/tests/**" = ["D", "E501"]
"states.py" = ["N801", "ARG003"]
